language: node_js
node_js:
  - '8.11.3'

cache: yarn

install:
  - yarn global add lerna jest now
  - lerna bootstrap

matrix:
  include:
    - name: Platform Pipeline
      env: PACKAGE_LOCATION=packages/platform PACKAGE_NAME=platform
    - name: Website Pipeline
      env: PACKAGE_LOCATION=packages/website PACKAGE_NAME=website

script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build

deploy:
  provider: script
  script: now public --token $NOW_TOKEN
  skip_cleanup: true
  app: $PACKAGE_NAME
